- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  
  - name: enable and start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: delete html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download the forntend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      path: /tmp/forntend.zip
  
  - name: Unzip frontend code
    ansible.builtin.unarchive:
     src: /tmp/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes

  - name: copy config file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf
  
  - name: restart nginx
    ansible.builtin.service:
      state: restart
      name: nginx